# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZCNetwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ZCNetwork
  pod 'ReactiveObjC',"~> 3.1.1"
  pod 'AFNetworking',"~> 3.2.1"
end
